dependencies:
  task:
    - vim/plug
install:
  pkg:
    - git
  backup:
    - "{home}/.vimrc"
  mkdir:
    - "{home}/.vim"
    - "{home}/.vim/colors"
  ln:
    - Linking .vimrc | {repo}/config/.vimrc > {home}/
    - Linking dalek colorscheme | {repo}/config/vim/dalek.vim > {home}/.vim/colors/
  cmd:
    - vim -c :PlugInstall -c :q -c :q
