dependencies:
  task:
    - zsh/zsh
    - zsh/ohmyzsh
install:
  mkdir:
    - "{home}/.rc"
  ln:
    - Linking .zshrc | {repo}/config/.zshrc > {home}
    - Linking AddIn-Folder | {repo}/config/.rc-temp > {home}
    - Linking theme senaex | {repo}/config/senaex.zsh-theme > /usr/local/zsh/oh-my-zsh/themes
