dependencies:
  task:
    zsh
install:
  mkdir:
    - "{home}/.old"
  cmd:
    - Moving old files to ~/.old | mv {home}/.zshrc {home}/.rc {home}/.rc-temp -t {home}/.old
  mkdir:
    - "{home}/.rc"
  ln:
    - Linking .zshrc | {repo}/config/.zshrc > {home}
    - Linking AddIn-Folder | {repo}/config/.rc-temp > {home}
    - Linking theme senaex | {repo}/config/senaex.zsh-theme > /usr/local/zsh/oh-my-zsh/themes
    - Linking theme lennart | {repo}/config/lennart.zsh-theme > /usr/local/zsh/oh-my-zsh/themes
